### ISSUE TITLE
Not using node resolution in library

### ISSUE THREAD

**Issue by willemneal** [aspkg/as-json#2]
https://github.com/JairusSW/as-kati/blob/558296738f2fff45e574f8d10969c165f2b79ffb/assembly/index.ts#L5

Should be 

```ts
import { StringSink } from 'as-string-sink`
```

Did this not work?

**Comment by JairusSW** [comment]
Hrmm... Let me try. I think it resolves to look in the `~lib/` directory. I get an error stating that it can't find `~lib/as-string-sink`...

**Comment by JairusSW** [comment]
Hrm.. Let me try. Updating to the latest version...

**Comment by JairusSW** [comment]
Oh, great! Looks like it got fixed, @willemneal . Pushing changes...
