### ISSUE TITLE
Crash decoding boolean in embedded struct

### ISSUE THREAD

**Issue by cohix** [aspkg/as-json#8]
Given these classes:
```
// @ts-ignore
@json
class JSONSchema {
    firstName: string
    lastName: string
    age: i32
    meta: Meta
}

// @ts-ignore
@json
class Meta {
    country: string
    awesome: boolean
}
```

If I attempt to decode JSON, it crashes any time the `boolean` exists. If I remove it, the crash no longer happens. Unsure if it's related to the data type or not.

Error:
```
Index out of range; file: ~lib/array.ts, line: 99, col: 42"
```

**Comment by JairusSW** [comment]
Hmm... Going to re-create this.

**Comment by JairusSW** [comment]
Fixed it. Made a new algorithm. :)
